steps:
- block: ":ballot_box_with_ballot:"
  prompt: "We robots have questions. Many questions."
  fields:
  - text: "How many steps to create?"
    key: "generated-number"
    hint: "Think of any number. But a positive number. And not too large, please."
  - select: "Do you have a favorite?"
    key: "favourite-thing"
    options:
    - label: ":green_apple:"
      value: "green_apple"
    - label: ":apple:"
      value: "apple"
    - label: ":pear:"
      value: "pear"
    - label: ":cherries:"
      value: "cherries"
    - label: ":strawberry:"
      value: "strawberry"

- label: ":pipeline:"
  command: buildkite-agent pipeline upload .buildkite/pipeline.ask-to-continue.yml

- command: "echo tests.sh"
  label: "Test %n"
  parallelism: 5
