env:
  # Scenario set versions to use in scorecard reporting.
  DEFAULT_CONSTANT_V: 5
  DEFAULT_SIDE_V: 11
  # These versions can be optionally overridden.
  SIDE_V: "${SIDE_V:-$DEFAULT_SIDE_V}"
  CONSTANT_V: "${CONSTANT_V:-$DEFAULT_CONSTANT_V}"
steps:
  - command: echo "test"
