steps:
  - label: ":bazel: :bar_chart: p2_zip/exec Coverage"
    if_changed: "p2_zip/exec/**"
    depends_on:
      - bazel-test
    command: |
      echo "./buildkite/ci/bin/p2_exec_coverage.sh"
    artifact_paths:
      - coverage_report/**/*
      - coverage_summary.txt
    plugins:
      - docker#v5.12.0:
          <<: *docker_params
          mount-buildkite-agent: true
          environment:
            - "GH_TOKEN"
