---
steps:
- key: npm-tooling-build
  group: ":node::hammer_and_wrench: Platform NPM Tooling Build"
  steps:
  - key: root-test
    label: ":node::hammer_and_wrench: Platform NPM Tooling :: Node Tests"
    command: echo "test"
    branches:
    - "!gh-readonly-queue/*"
    depends_on: []
  - key: root-build
    label: ":node::hammer_and_wrench: Platform NPM Tooling :: Node Build/Bundle"
    command: echo "test"
    branches:
    - "!gh-readonly-queue/*"
    depends_on:
    - root-test
    artifact_paths: "./dist/*"
  - key: root-publish
    label: ":node::package: Platform NPM Tooling :: Publish"
    command: echo "test"
    branches:
    - "!gh-readonly-queue/*"
    depends_on:
    - root-build
  depends_on: []
